// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `level_to_i32`, `sink_cell`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DartSinkLayer`, `MessageVisitor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `on_event`, `record_debug`

/// Open a stream of Rust `tracing` events to Dart.
///
/// The tracing subscriber is installed on the first call; subsequent calls just
/// replace the active sink. The subscriber captures every level (TRACE..ERROR);
/// filtering by level is done on the Dart side so the user can change it live.
Stream<LogEntry> createLogStream() =>
    RustLib.instance.api.crateApiLoggingCreateLogStream();

/// A single tracing event forwarded from Rust to Dart.
class LogEntry {
  /// Milliseconds since the Unix epoch.
  final PlatformInt64 timeMillis;

  /// Log level: 0=Trace, 1=Debug, 2=Info, 3=Warn, 4=Error.
  final int level;

  /// The event target (usually the module path).
  final String target;

  /// The rendered message (the `message` field plus any other fields).
  final String message;

  const LogEntry({
    required this.timeMillis,
    required this.level,
    required this.target,
    required this.message,
  });

  @override
  int get hashCode =>
      timeMillis.hashCode ^ level.hashCode ^ target.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogEntry &&
          runtimeType == other.runtimeType &&
          timeMillis == other.timeMillis &&
          level == other.level &&
          target == other.target &&
          message == other.message;
}
